# Data Manipulation with Pandas

Pandas is a powerful Python library for data manipulation and analysis, particularly useful when working with structured data. Let's explore how to use it effectively.

## Importing Pandas
The first step in using pandas is to import the library.

In [1]:
import pandas as pd

---

### Run this first: create the data files

Everything in this notebook reads from files. Run this one cell and every example
works, on any machine, with nothing to download.

It creates `airtravel.csv` (exactly as the original is formatted, quirky headers and
all), plus a set of orders and customers files we will use for the real examples.

In [ ]:
import os, random

# 1. airtravel.csv, in its original shape. Note the quotes and the spaces after commas.
with open("airtravel.csv", "w", encoding="utf-8") as f:
    f.write('"Month", "1958", "1959", "1960"\n')
    for row in [
        ("JAN", 340, 360, 417), ("FEB", 318, 342, 391), ("MAR", 362, 406, 419),
        ("APR", 348, 396, 461), ("MAY", 363, 420, 472), ("JUN", 435, 472, 535),
        ("JUL", 491, 548, 622), ("AUG", 505, 559, 606), ("SEP", 404, 463, 508),
        ("OCT", 359, 407, 461), ("NOV", 310, 362, 390), ("DEC", 337, 405, 432),
    ]:
        f.write(f'"{row[0]}",  {row[1]},  {row[2]},  {row[3]}\n')

# 2. a realistic orders file, with the mess real files have
with open("orders.csv", "w", encoding="utf-8") as f:
    f.write("order_id,customer_id,item,category,quantity,unit_price,order_date,country,status\n")
    f.write("1001,101,Laptop Pro,Electronics,1,450000,2026-01-15,NG,completed\n")
    f.write("1002,102,Phone X,Electronics,2,180000,2026-01-18,GH,completed\n")
    f.write("1003,101,Wireless Mouse,Accessories,3,8000,2026-02-03,NG,completed\n")
    f.write("1004,103,Laptop Pro,Electronics,1,520000,2026-02-11,NG,pending\n")
    f.write("1005,104,Monitor 27,Electronics,2,95000,2026-02-20,KE,completed\n")
    f.write("1006,102,Wireless Mouse,Accessories,1,7500,2026-03-02,GH,cancelled\n")
    f.write("1007,103,Keyboard,Accessories,2,15000,2026-03-14,NG,completed\n")
    f.write("1008,105,Phone X,Electronics,1,,2026-03-19,KE,completed\n")
    f.write("1009,101,Monitor 27,Electronics,1,95000,2026-04-01,NG,completed\n")
    f.write("1010,106,Headset,Accessories,4,22000,2026-04-08,GH,completed\n")
    f.write("1011,102,Laptop Pro,Electronics,1,450000,,NG,pending\n")
    f.write("1012,999,Keyboard,Accessories,1,15000,2026-04-22,NG,completed\n")
    f.write("1003,101,Wireless Mouse,Accessories,3,8000,2026-02-03,NG,completed\n")

# 3. the customers dimension table
with open("customers.csv", "w", encoding="utf-8") as f:
    f.write("customer_id,name,segment,signup_date,country\n")
    f.write("101,Ahmed Oladapo,enterprise,2025-06-01,NG\n")
    f.write("102,Lahla Mensah,smb,2025-08-14,GH\n")
    f.write("103,Judith Eze,enterprise,2025-09-30,NG\n")
    f.write("104,Uche Okafor,smb,2026-01-05,KE\n")
    f.write("105,Grace Wanjiru,smb,2026-01-20,KE\n")
    f.write("107,Samuel Adeyemi,enterprise,2026-02-11,NG\n")

# 4. a second month of orders, for the concat example
with open("orders_may.csv", "w", encoding="utf-8") as f:
    f.write("order_id,customer_id,item,category,quantity,unit_price,order_date,country,status\n")
    f.write("1013,104,Laptop Pro,Electronics,1,450000,2026-05-04,KE,completed\n")
    f.write("1014,101,Headset,Accessories,2,22000,2026-05-12,NG,completed\n")

print("Created:")
for name in ["airtravel.csv", "orders.csv", "customers.csv", "orders_may.csv"]:
    print(f"  {name}  ({os.path.getsize(name)} bytes)")

print()
print("raw airtravel.csv, first 3 lines:")
with open("airtravel.csv", encoding="utf-8") as f:
    for _ in range(3):
        print(repr(f.readline()))

In [ ]:
# Load the air travel file so the cells below this one work
import pandas as pd

df = pd.read_csv("airtravel.csv")
df.head()

In [2]:
df_1 = pd.read_csv('airtravel.csv')
df_2 = pd.read_csv('airtravel.csv')
df_3 = pd.read_csv('airtravel.csv')

In [12]:
df.head()

  Month   "1958"   "1959"   "1960"
0   JAN      340      360      417
1   FEB      318      342      391
2   MAR      362      406      419
3   APR      348      396      461
4   MAY      363      420      472

In [17]:
df.tail()

   Month   "1958"   "1959"   "1960"
7    AUG      505      559      606
8    SEP      404      463      508
9    OCT      359      407      461
10   NOV      310      362      390
11   DEC      337      405      432

In [23]:
df.sample(5)

   Month   "1958"   "1959"   "1960"
8    SEP      404      463      508
2    MAR      362      406      419
4    MAY      363      420      472
6    JUL      491      548      622
11   DEC      337      405      432

## Reading Data
Pandas can read data from various formats such as CSV, Excel, JSON, and SQL. Here, we will focus on reading from CSV.

**Tip:** type `df.to_` in a code cell and press **Tab** to see every export method
pandas offers: `to_csv`, `to_excel`, `to_json`, `to_parquet`, `to_sql`, `to_dict`,
`to_clipboard` and more. The same trick works for `pd.read_` to see every reader.

In [24]:
# Reading a CSV file into a DataFrame
df = pd.read_csv('airtravel.csv')
print(df.head())  # Display the first 5 rows of the DataFrame

  Month   "1958"   "1959"   "1960"
0   JAN      340      360      417
1   FEB      318      342      391
2   MAR      362      406      419
3   APR      348      396      461
4   MAY      363      420      472

## Writing Data
You can write DataFrames to different formats. Here’s how to write data back to a CSV file.

In [ ]:
# Writing a DataFrame to a CSV file
df.to_csv('output.csv', index=False)

In [26]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Month    12 non-null     object
 1    "1958"  12 non-null     int64
 2    "1959"  12 non-null     int64
 3    "1960"  12 non-null     int64
dtypes: int64(3), object(1)
memory usage: 516.0+ bytes
None

In [27]:
print(df.describe())

           "1958"      "1959"      "1960"
count   12.000000   12.000000   12.000000
mean   381.000000  428.333333  476.166667
std     64.530472   69.830097   77.737125
min    310.000000  342.000000  390.000000
25%    339.250000  387.500000  418.500000
50%    360.500000  406.500000  461.000000
75%    411.750000  465.250000  514.750000
max    505.000000  559.000000  622.000000

In [28]:
print(df.columns)

Index(['Month', ' "1958"', ' "1959"', ' "1960"'], dtype='object')

In [29]:
print(df.shape)

(12, 4)

## Inspecting Data
When working with large datasets, it's important to inspect the data to understand its structure.

In [30]:
# Viewing basic information about the DataFrame
print(df.info())  # Shows column data types and non-null counts
print(df.describe())  # Summary statistics for numerical columns
print(df.columns)  # Column names
print(df.shape)  # Dimensions of the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Month    12 non-null     object
 1    "1958"  12 non-null     int64
 2    "1959"  12 non-null     int64
 3    "1960"  12 non-null     int64
dtypes: int64(3), object(1)
memory usage: 516.0+ bytes
None
           "1958"      "1959"      "1960"
count   12.000000   12.000000   12.000000
mean   381.000000  428.333333  476.166667
std     64.530472   69.830097   77.737125
min    310.000000  342.000000  390.000000
25%    339.250000  387.500000  418.500000
50%    360.500000  406.500000  461.000000
75%    411.750000  465.250000  514.750000
max    505.000000  559.000000  622.000000
Index(['Month', ' "1958"', ' "1959"', ' "1960"'], dtype='object')
(12, 4)

---

## Practice: Inspecting and loading data properly

### Series and DataFrame: two objects, not one

A **Series** is one column. A **DataFrame** is a collection of Series sharing an index.
Almost every confusing pandas error comes from not knowing which one you are holding.

In [ ]:
import pandas as pd

one_column = df["Month"]              # single brackets -> Series
two_columns = df[["Month"]]           # double brackets -> DataFrame with one column

print(type(one_column).__name__)
print(type(two_columns).__name__)
print()
print(one_column.head(3))
print()
print(two_columns.head(3))

Single brackets give you a Series. Double brackets give you a DataFrame.
`df["a"]` and `df[["a"]]` look almost identical and behave differently, and that is
worth ten minutes of confusion now instead of an hour later.

In [ ]:
# A Series has an index and values
s = df["Month"]

print(f"name:   {s.name}")
print(f"dtype:  {s.dtype}")
print(f"shape:  {s.shape}")
print(f"index:  {list(s.index)[:5]}")
print(f"values: {s.values[:5]}")

### The messy column names, and how to stop them happening

Look at what `read_csv` produced from `airtravel.csv`.

In [ ]:
print(list(df.columns))

`' "1958"'` with a leading space and literal quote marks. That is why every later
cell has to write `df[' "1958"']`, which nobody will ever type correctly twice.

The file has spaces after the commas, so pandas treats them as part of the value.
One argument fixes it at load time.

In [ ]:
clean = pd.read_csv("airtravel.csv", skipinitialspace=True)
print(list(clean.columns))
clean.head(3)

`skipinitialspace=True` strips the space after each comma, so the quotes are
recognised as quoting and get removed. Fix it at the source rather than renaming
afterwards, every time you can.

In [ ]:
# When you cannot fix it at load time, clean the names in one line
messy = pd.read_csv("airtravel.csv")

messy.columns = (
    messy.columns
    .str.strip()                    # remove surrounding whitespace
    .str.replace('"', "", regex=False)
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

print(list(messy.columns))
messy.head(3)

Standardising column names on the way in (lowercase, underscores, no spaces) is a
small habit that saves real time. `df.order_date` works, `df['Order Date']` does not.

In [ ]:
# The read_csv arguments actually worth knowing
orders = pd.read_csv(
    "orders.csv",
    parse_dates=["order_date"],        # real dates, not strings
    dtype={"customer_id": "Int64"},    # capital I: an integer that allows nulls
)

print(orders.dtypes)
print()
orders.head()

| Argument | What it does |
|---|---|
| `usecols=["a", "b"]` | Read only these columns. Faster and smaller |
| `nrows=1000` | Read only the first N rows, for a quick look at a huge file |
| `skiprows=3` | Skip junk at the top of the file |
| `na_values=["N/A", "-", "NULL"]` | Treat these strings as missing |
| `parse_dates=["order_date"]` | Convert to real dates at load time |
| `dtype={"id": "Int64"}` | Force a column's type |
| `skipinitialspace=True` | Strip the space after each comma |
| `encoding="utf-8"` | Say it explicitly, always |
| `chunksize=50000` | Read in pieces, for files bigger than memory |

In [ ]:
# usecols and nrows: peek at a big file cheaply
peek = pd.read_csv("orders.csv", usecols=["order_id", "item", "unit_price"], nrows=4)
peek

In [ ]:
# The four inspection calls you run on every new dataset, in this order
orders = pd.read_csv("orders.csv", parse_dates=["order_date"])

print("shape:", orders.shape)          # rows, columns. an attribute, no parentheses
print()
orders.info()                          # a method, needs parentheses

Notice `orders.shape` has no parentheses and `orders.info()` does. `shape` is a data
attribute holding a value. `info()` is a method that does work. Same distinction as
`raw.strip` versus `raw.strip()` on a string.

Quick check: if the output starts with `<bound method`, you forgot the parentheses.

In [ ]:
orders.describe()            # numeric columns only, by default

In [ ]:
orders.describe(include="all")      # everything, including text and dates

In [ ]:
# What is actually in each column
print(orders["country"].value_counts())
print()
print(orders["status"].value_counts(dropna=False))     # dropna=False shows nulls too
print()
print(orders["category"].value_counts(normalize=True))  # as proportions

In [ ]:
# The data quality checks you run before trusting anything
print("nulls per column:")
print(orders.isna().sum())

print()
print("null rate as a percentage:")
print((orders.isna().mean() * 100).round(1))

print()
print(f"duplicate rows: {orders.duplicated().sum()}")
print(f"duplicate order_ids: {orders['order_id'].duplicated().sum()}")
print(f"distinct customers: {orders['customer_id'].nunique()}")

`isna().sum()` counts the nulls. `isna().mean()` gives the proportion, because
`True` counts as 1 and `False` as 0, so the average of a boolean column is the rate.
That trick works everywhere in pandas.

In [ ]:
# How much memory is this actually using?
orders.info(memory_usage="deep")

### Your turn: tasks

**Task 1.** Load `airtravel.csv` with `skipinitialspace=True` and print the column
names, the shape and the dtypes.

**Task 2.** Load only the `order_id`, `item` and `quantity` columns from `orders.csv`,
and only the first 5 rows.

**Task 3.** Print `describe()` for `orders.csv` and say in a comment which column has
the widest spread between its minimum and maximum.

**DE Task 4.** Write a function `profile(df)` that prints, for any DataFrame: the
shape, the null count per column, the null rate as a percentage, the number of
duplicate rows, and the dtype of each column. Run it on `orders.csv`.

**DE Task 5.** Load `orders.csv` and clean the column names so they are all lowercase
with underscores and no spaces, in one chained expression.

**DE Task 6.** Print the value counts of `status` and `country`, and the percentage
of orders that are not `completed`.

In [ ]:
# Task 1 answer

In [ ]:
# Task 2 answer

In [ ]:
# Task 3 answer

In [ ]:
# DE Task 4 answer

In [ ]:
# DE Task 5 answer

In [ ]:
# DE Task 6 answer

## Selecting Data
You can select specific rows, columns, or subsets of your DataFrame using different methods.

In [31]:
df.head(2)

  Month   "1958"   "1959"   "1960"
0   JAN      340      360      417
1   FEB      318      342      391

In [32]:
df.columns

Index(['Month', ' "1958"', ' "1959"', ' "1960"'], dtype='object')

In [36]:
popo = df[['Month', ' "1958"']]

In [38]:
popo.to_csv('popo.csv')

In [44]:
a = df[' "1958"'] > 400

In [45]:
a

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7      True
8      True
9     False
10    False
11    False
Name:  "1958", dtype: bool

In [46]:
df[a]

  Month   "1958"   "1959"   "1960"
5   JUN      435      472      535
6   JUL      491      548      622
7   AUG      505      559      606
8   SEP      404      463      508

In [41]:
print(df[df[' "1958"'] > 400])

  Month   "1958"   "1959"   "1960"
5   JUN      435      472      535
6   JUL      491      548      622
7   AUG      505      559      606
8   SEP      404      463      508

**Reference: selecting** (replace the placeholder names with your own columns)

```python
df["column_name"]                  # one column, as a Series
df[["column1", "column2"]]         # several columns, as a DataFrame
df.iloc[0]                         # first row, by position
df.iloc[0:3]                       # first 3 rows, stop excluded
df.loc[0:3]                        # FOUR rows, stop included
df[df["column_name"] > 10]         # rows matching a condition
```

Worked examples on the real data are in the practice section below.

---

## Practice: Selecting and filtering

### `.loc` and `.iloc`: the two you must not mix up

- `.loc[rows, columns]` selects by **label**. The stop is **included**.
- `.iloc[rows, columns]` selects by **position**. The stop is **excluded**, like a list.

If you only remember one thing: `loc` = label, `iloc` = index position.

In [ ]:
import pandas as pd
orders = pd.read_csv("orders.csv", parse_dates=["order_date"])

print("iloc[0] gives the first row as a Series:")
print(orders.iloc[0])
print()
print("iloc[0:3] gives 3 rows. 0, 1, 2. Not 3.")
print(orders.iloc[0:3][["order_id", "item"]])

In [ ]:
print("loc[0:3] gives FOUR rows, because loc includes the stop label:")
print(orders.loc[0:3][["order_id", "item"]])

That difference bites everyone once. `iloc[0:3]` gives 3 rows, `loc[0:3]` gives 4.
`loc` is inclusive because labels are not necessarily numbers, so "up to and
including this label" is the only definition that makes sense.

In [ ]:
# Rows and columns together
print(orders.loc[0:2, ["order_id", "item", "unit_price"]])
print()
print(orders.iloc[0:2, 0:3])          # first 2 rows, first 3 columns
print()
print(orders.loc[5, "item"])          # one cell, by label
print(orders.iloc[5, 2])              # the same cell, by position

In [ ]:
# Filtering: a boolean mask is just a Series of True and False
mask = orders["unit_price"] > 100000

print(mask.head(8))
print()
print(f"{mask.sum()} rows match")       # True counts as 1
print()
print(orders[mask][["order_id", "item", "unit_price"]])

### The parentheses rule, which trips up literally everyone

Combining conditions in pandas uses `&`, `|` and `~`, **not** `and`, `or`, `not`.
And every condition must be wrapped in its own parentheses, because `&` binds more
tightly than `>` does.

In [ ]:
# This is correct
result = orders[(orders["unit_price"] > 50000) & (orders["country"] == "NG")]
print(result[["order_id", "item", "unit_price", "country"]])

In [ ]:
# Forget the parentheses and you get a confusing error, not a wrong answer
try:
    orders[orders["unit_price"] > 50000 & orders["country"] == "NG"]
except Exception as e:
    print(f"{type(e).__name__}: {e}")

print()
# Use "and" instead of "&" and you get a different confusing error
try:
    orders[(orders["unit_price"] > 50000) and (orders["country"] == "NG")]
except Exception as e:
    print(f"{type(e).__name__}: {str(e)[:120]}")

"The truth value of a Series is ambiguous" is pandas saying: you gave me a whole
column of True and False and asked me to decide if it is one True or one False.
Use `&` for element-by-element AND, `|` for OR, `~` for NOT.

In [ ]:
# The three operators in use
electronics_ng = orders[(orders["category"] == "Electronics") & (orders["country"] == "NG")]
gh_or_ke = orders[(orders["country"] == "GH") | (orders["country"] == "KE")]
not_completed = orders[~(orders["status"] == "completed")]

print(f"electronics in NG: {len(electronics_ng)}")
print(f"GH or KE:          {len(gh_or_ke)}")
print(f"not completed:     {len(not_completed)}")

In [ ]:
# isin, between and str: shorter than chaining ORs
print(orders[orders["country"].isin(["GH", "KE"])][["order_id", "country"]])
print()
print(orders[orders["unit_price"].between(10000, 100000)][["order_id", "unit_price"]])
print()
print(orders[orders["item"].str.contains("Laptop", na=False)][["order_id", "item"]])
print()
print(orders[orders["status"] != "completed"][["order_id", "status"]])

`na=False` on `.str.contains` matters. Without it, a null in the column produces
`NaN` rather than `False`, and pandas refuses to use that as a mask.

In [ ]:
# query(): the same filter, written like SQL. Easier to read for long conditions.
print(orders.query("unit_price > 50000 and country == 'NG'")[["order_id", "item", "unit_price"]])
print()
threshold = 100000
print(orders.query("unit_price > @threshold")[["order_id", "unit_price"]])

Inside `query`, `@threshold` means "the Python variable called threshold".
And note that `query` does use the words `and` / `or`, unlike bracket filtering.
Yes, that is inconsistent. Yes, it catches people out.

### `SettingWithCopyWarning`, and how to never see it again

This is the most common pandas warning in the world, and the fix is one word.

In [ ]:
import warnings

# The pattern that causes it: filter, then assign to the result
subset = orders[orders["country"] == "NG"]

with warnings.catch_warnings(record=True) as caught:
    warnings.simplefilter("always")
    subset["discounted"] = subset["unit_price"] * 0.9
    if caught:
        print(f"WARNING: {caught[0].category.__name__}")
    else:
        print("no warning on this pandas version, but the habit below is still right")

print(subset[["order_id", "unit_price", "discounted"]].head(3))

The problem is that `orders[...]` may hand you a **view** onto the original rather
than a new DataFrame, so pandas cannot tell whether you meant to change the subset
or the original. Behaviour differs between pandas versions, which is worse than a
clear error.

The fix, in both pandas 2 and pandas 3: **add `.copy()` when you intend a new,
independent table.**

In [ ]:
subset = orders[orders["country"] == "NG"].copy()      # explicit, no ambiguity
subset["discounted"] = subset["unit_price"] * 0.9

print(subset[["order_id", "unit_price", "discounted"]].head(3))
print()
print(f"original untouched? {'discounted' not in orders.columns}")

In [ ]:
# When you DO want to change the original, use .loc on the original
orders_copy = orders.copy()
orders_copy.loc[orders_copy["country"] == "NG", "region"] = "West Africa"
orders_copy.loc[orders_copy["country"] == "KE", "region"] = "East Africa"
orders_copy.loc[orders_copy["country"] == "GH", "region"] = "West Africa"

print(orders_copy[["order_id", "country", "region"]].head(6))

**The rule:** to change the original, `df.loc[mask, "column"] = value`.
To work on a subset, `df[mask].copy()` first. Never assign into a filtered result
you did not copy.

### Your turn: tasks

**Task 1.** From `orders.csv`, select the `order_id` and `item` columns for the first
4 rows, using `iloc`, then the same thing using `loc`. Note the row count difference
if you use `0:4` in both.

**Task 2.** Filter for orders where `quantity` is greater than 1.

**Task 3.** Filter for `Accessories` orders in `NG`, using `&` and parentheses.

**Task 4.** Rewrite Task 3 using `query()`.

**DE Task 5.** Find every order that is **not** completed, in a country that is not
`NG`, using `~` and `&`.

**DE Task 6.** Find every order whose `item` contains the word "Laptop", and print
the total value (quantity times unit price) of those orders.

**DE Task 7.** Build a filtered copy of the NG orders, add a column `vat` that is 7.5%
of `unit_price`, and prove the original DataFrame has no `vat` column afterwards.

In [ ]:
# Task 1 answer

In [ ]:
# Task 2 answer

In [ ]:
# Task 3 answer

In [ ]:
# Task 4 answer

In [ ]:
# DE Task 5 answer

In [ ]:
# DE Task 6 answer

In [ ]:
# DE Task 7 answer

## Filtering Data
Filtering allows you to extract specific data based on conditions.

**Reference: filtering**

```python
filtered_df = df[df["column_name"] > threshold]
filtered_df = df[(df["a"] > 10) & (df["b"] == "x")]      # & not "and"
filtered_df = df[df["a"].isin([1, 2, 3])]
filtered_df = df.query("a > 10 and b == 'x'")
```

Note the parentheses around each condition. They are not optional.

In [ ]:
1, 3, 4, 2, 3, 5, 2, 3, 10, 25

## Handling Missing Data
Pandas provides easy ways to detect, fill, or drop missing values.

In [48]:
df.dropna()

   Month   "1958"   "1959"   "1960"
0    JAN      340      360      417
1    FEB      318      342      391
2    MAR      362      406      419
3    APR      348      396      461
4    MAY      363      420      472
5    JUN      435      472      535
6    JUL      491      548      622
7    AUG      505      559      606
8    SEP      404      463      508
9    OCT      359      407      461
10   NOV      310      362      390
11   DEC      337      405      432

**Reference: missing data**

```python
df.isna().sum()                      # count of nulls per column
df.isna().mean() * 100               # null rate as a percentage

df.dropna()                          # drop rows with ANY null. usually too aggressive
df.dropna(subset=["amount"])         # drop only where this column is null
df.dropna(axis=1)                    # drop COLUMNS containing nulls

df.fillna(0)                         # replace nulls with 0
df.fillna(df.mean(numeric_only=True))  # column means. numeric_only is required
```

`df.fillna(df.mean())` without `numeric_only=True` raises a `TypeError` on any table
that has a text column. Worked examples are in the practice section below.

---

## Practice: Missing data and data types

### First, see what is missing

In [ ]:
import pandas as pd
orders = pd.read_csv("orders.csv", parse_dates=["order_date"])

print(orders.isna().sum())
print()
print("rows with ANY null:")
print(orders[orders.isna().any(axis=1)])

`axis=1` means "look across the row". `axis=0` means "look down the column".
Whenever a pandas function takes `axis`, that is what it is asking.

In [ ]:
# Three ways to fill, and they are not interchangeable
filled_zero = orders["unit_price"].fillna(0)
filled_mean = orders["unit_price"].fillna(orders["unit_price"].mean())
filled_ffill = orders["unit_price"].ffill()          # carry the previous value forward

comparison = pd.DataFrame({
    "original": orders["unit_price"],
    "fill_0": filled_zero,
    "fill_mean": filled_mean.round(0),
    "ffill": filled_ffill,
})
comparison

Choosing wrongly here quietly corrupts a report. Filling a missing price with `0`
makes your revenue too low. Filling with the mean invents money that never existed.
For a price, the honest answer is usually to leave it null and exclude the row from
the revenue calculation, saying so in the output.

`ffill` belongs to time series, where carrying the last known reading forward is
meaningful. It is the wrong default for anything else.

In [ ]:
# df.fillna(df.mean()) fails on a table with text columns. This is the fix.
try:
    orders.fillna(orders.mean())
except TypeError as e:
    print(f"TypeError: {str(e)[:90]}")

print()
numeric_means = orders.mean(numeric_only=True)
print(numeric_means)
print()
filled = orders.fillna(numeric_means)
print(f"nulls before: {orders.isna().sum().sum()}, after: {filled.isna().sum().sum()}")

In [ ]:
# dropna: be specific about what you are dropping
print(f"all rows:                      {len(orders)}")
print(f"dropna() any null anywhere:    {len(orders.dropna())}")
print(f"dropna(subset=['unit_price']): {len(orders.dropna(subset=['unit_price']))}")
print(f"dropna(how='all'):             {len(orders.dropna(how='all'))}")
print(f"dropna(axis=1) drops COLUMNS:  {orders.dropna(axis=1).shape}")

A bare `dropna()` drops a row if **any** column is null. On a wide table that can
delete most of your data because of one mostly-empty column nobody uses.
Always pass `subset=` and name the columns that actually matter.

### Types: where silent wrongness lives

In [ ]:
print(orders.dtypes)
print()
print(f"unit_price is numeric:  {pd.api.types.is_numeric_dtype(orders['unit_price'])}")
print(f"order_date is a date:   {pd.api.types.is_datetime64_any_dtype(orders['order_date'])}")

In [ ]:
# The classic disaster: a numeric column read as text because of one bad value
messy = pd.DataFrame({"amount": ["1000", "2500", "N/A", "750", ""]})
print(messy.dtypes)

# Summing it does something, and that something is wrong
print(f"sum of a text column: {messy['amount'].sum()!r}")

In [ ]:
# to_numeric with errors="coerce" turns anything unparseable into NaN
messy["amount_clean"] = pd.to_numeric(messy["amount"], errors="coerce")
print(messy)
print()
print(f"dtype now: {messy['amount_clean'].dtype}")
print(f"sum:       {messy['amount_clean'].sum()}")
print(f"coerced to null: {messy['amount_clean'].isna().sum()} value(s)")

`errors="coerce"` is the single most useful argument in pandas cleaning. It says
"convert what you can, make the rest null, do not crash". Then you decide what to do
with the nulls, deliberately, instead of the job dying on row 4,000,000.

Always report how many values it coerced. A silent coercion is a silent data loss.

In [ ]:
# astype vs to_numeric: astype is strict, to_numeric is forgiving
try:
    messy["amount"].astype(float)
except ValueError as e:
    print(f"astype raises: {str(e)[:70]}")

print("to_numeric coerces instead:", list(pd.to_numeric(messy["amount"], errors="coerce")))

In [ ]:
# Dates: the same story
raw_dates = pd.Series(["2026-01-15", "15/01/2026", "not a date", None])

print(pd.to_datetime(raw_dates, errors="coerce", format="mixed", dayfirst=False))
print()
print("with an explicit format, anything that does not match becomes NaT:")
print(pd.to_datetime(raw_dates, errors="coerce", format="%Y-%m-%d"))

`NaT` is "not a time", the date version of `NaN`. Specifying `format=` explicitly is
both faster and safer: without it, pandas guesses, and `03/04/2026` is the 3rd of
April in Lagos and the 4th of March in New York.

In [ ]:
# The .dt accessor: everything you want from a date column
orders["year"] = orders["order_date"].dt.year
orders["month"] = orders["order_date"].dt.month
orders["month_name"] = orders["order_date"].dt.month_name()
orders["day_of_week"] = orders["order_date"].dt.day_name()
orders["partition"] = orders["order_date"].dt.strftime("%Y-%m")

orders[["order_id", "order_date", "year", "month_name", "day_of_week", "partition"]].head(6)

In [ ]:
# The .str accessor: the same idea for text columns
orders["item_lower"] = orders["item"].str.lower()
orders["item_length"] = orders["item"].str.len()
orders["first_word"] = orders["item"].str.split(" ").str[0]
orders["is_laptop"] = orders["item"].str.contains("Laptop", na=False)

orders[["item", "item_lower", "item_length", "first_word", "is_laptop"]].head(6)

### Duplicates

In [ ]:
print(f"fully duplicated rows: {orders.duplicated().sum()}")
print(orders[orders.duplicated(keep=False)][["order_id", "item", "order_date"]])
print()
print(f"duplicate order_ids: {orders['order_id'].duplicated().sum()}")

deduped = orders.drop_duplicates(subset=["order_id"], keep="first")
print(f"before: {len(orders)}, after: {len(deduped)}")

`keep="first"` keeps the earliest, `keep="last"` the latest, `keep=False` marks
**every** copy as a duplicate, which is what you want when you are inspecting them
rather than removing them.

Always pass `subset=` with your business key. Two rows can differ in a `loaded_at`
timestamp and still be the same order.

### Your turn: tasks

**Task 1.** Print the null count and the null percentage for every column of
`orders.csv`.

**Task 2.** Show only the rows that have at least one null.

**Task 3.** Fill the missing `unit_price` with 0 in a copy, and separately with the
column mean in another copy. Print both and say in a comment which you would use for
a revenue report, and why.

**Task 4.** Convert the `order_date` column to a real date and add `year`, `month` and
`partition` (as `YYYY-MM`) columns.

**DE Task 5.** Write a function `to_number(series)` that uses `to_numeric` with
coercion and prints how many values it turned into nulls. Run it on a Series
containing `["1000", "2,500", "N/A", "", "750"]`. (The comma is a trap: strip it first.)

**DE Task 6.** Find the duplicate `order_id` values in `orders.csv`, show every copy,
then produce a deduplicated DataFrame keeping the first of each and report how many
rows were dropped.

**DE Task 7.** Write a function `type_check(df, expected)` where `expected` is a dict
like `{"order_id": "int", "unit_price": "float", "order_date": "datetime"}`. It should
print, for each column, whether the actual dtype matches what you expected.

In [ ]:
# Task 1 answer

In [ ]:
# Task 2 answer

In [ ]:
# Task 3 answer

In [ ]:
# Task 4 answer

In [ ]:
# DE Task 5 answer

In [ ]:
# DE Task 6 answer

In [ ]:
# DE Task 7 answer

## Grouping and Aggregating Data
Pandas makes it easy to group data by certain columns and perform aggregate operations (like sum, mean, etc.).

**Reference: grouping**

```python
df.groupby("category_column").mean(numeric_only=True)

df.groupby("category_column").agg({"column1": "mean", "column2": "sum"})

df.groupby("category_column").agg(            # named aggregation, better column names
    orders=("order_id", "count"),
    revenue=("amount", "sum"),
).reset_index()
```

---

## Practice: Grouping and aggregating

`groupby` is `GROUP BY`. If you can write the SQL, you can write the pandas.

```sql
SELECT country, SUM(revenue) FROM orders GROUP BY country
```
becomes
```python
orders.groupby("country")["revenue"].sum()
```

In [ ]:
import pandas as pd
orders = pd.read_csv("orders.csv", parse_dates=["order_date"])
orders["revenue"] = orders["quantity"] * orders["unit_price"]

print(orders.groupby("country")["revenue"].sum())
print()
print(orders.groupby("country")["revenue"].sum().sort_values(ascending=False))

That returns a **Series**, indexed by country. Add `.reset_index()` to get a normal
DataFrame back, which is usually what you want for exporting or merging.

In [ ]:
by_country = orders.groupby("country")["revenue"].sum().reset_index()
print(type(by_country).__name__)
by_country

In [ ]:
# Several aggregations at once
print(orders.groupby("country")["revenue"].agg(["count", "sum", "mean", "min", "max"]))

In [ ]:
# Different aggregations for different columns
result = orders.groupby("country").agg({
    "revenue": "sum",
    "quantity": "sum",
    "order_id": "count",
    "unit_price": "mean",
})
result

In [ ]:
# Named aggregation: the version you will actually want, because the columns get real names
summary = orders.groupby("country").agg(
    orders=("order_id", "count"),
    customers=("customer_id", "nunique"),
    total_revenue=("revenue", "sum"),
    avg_order_value=("revenue", "mean"),
    biggest_order=("revenue", "max"),
).reset_index()

summary["avg_order_value"] = summary["avg_order_value"].round(0)
summary.sort_values("total_revenue", ascending=False)

Compare the column names here with the ones from `agg(["count", "sum"])`. Named
aggregation produces a table you can hand to someone without explaining it.

In [ ]:
# Grouping by more than one column
multi = orders.groupby(["country", "category"]).agg(
    orders=("order_id", "count"),
    revenue=("revenue", "sum"),
).reset_index()

multi.sort_values("revenue", ascending=False)

In [ ]:
# Grouping by something you compute on the fly
by_month = orders.groupby(orders["order_date"].dt.strftime("%Y-%m")).agg(
    orders=("order_id", "count"),
    revenue=("revenue", "sum"),
).reset_index(names="month")

by_month

The null `order_date` on order 1011 simply does not appear. `groupby` drops null
keys by default. Pass `dropna=False` if a missing key is itself meaningful, which in
a data quality report it usually is.

In [ ]:
print("default, nulls dropped:")
print(orders.groupby("status", dropna=True)["order_id"].count())
print()
print("with dropna=False, you can see them:")
print(orders.groupby(orders["order_date"].dt.year, dropna=False)["order_id"].count())

In [ ]:
# transform: an aggregate broadcast back onto every row.
# This is the pandas answer to a SQL window function.
orders["country_total"] = orders.groupby("country")["revenue"].transform("sum")
orders["share_of_country"] = (orders["revenue"] / orders["country_total"] * 100).round(1)

orders[["order_id", "country", "revenue", "country_total", "share_of_country"]].head(8)

`transform` keeps the original number of rows, `agg` collapses them. That is the
whole difference, and it is exactly `SUM(...) OVER (PARTITION BY country)` versus
`GROUP BY country`.

In [ ]:
# pivot_table: a group-by with one of the keys turned into columns
pivot = orders.pivot_table(
    values="revenue",
    index="country",
    columns="category",
    aggfunc="sum",
    fill_value=0,
    margins=True,               # adds a total row and column
)
pivot

### Your turn: tasks

**Task 1.** Add a `revenue` column (quantity times unit price) to `orders.csv`.

**Task 2.** Total revenue per `category`, sorted highest first.

**Task 3.** For each `country`: the number of orders, the total revenue and the
average revenue, using named aggregation.

**Task 4.** Count the orders per `status`.

**DE Task 5.** Revenue per `customer_id`, showing only customers who spent more than
100,000. Sort highest first.

**DE Task 6.** Build a month-by-month summary: orders, distinct customers and revenue
per `YYYY-MM`, with the null date visible rather than silently dropped.

**DE Task 7.** Add a column showing each order's revenue as a percentage of its
category's total revenue, using `transform`.

**DE Task 8.** Build a pivot table of revenue with `country` down the side and
`status` across the top, filling gaps with 0 and including totals.

In [ ]:
# Task 1 answer

In [ ]:
# Task 2 answer

In [ ]:
# Task 3 answer

In [ ]:
# Task 4 answer

In [ ]:
# DE Task 5 answer

In [ ]:
# DE Task 6 answer

In [ ]:
# DE Task 7 answer

In [ ]:
# DE Task 8 answer

In [53]:
popo

   Month   "1958"
0    JAN      340
1    FEB      318
2    MAR      362
3    APR      348
4    MAY      363
5    JUN      435
6    JUL      491
7    AUG      505
8    SEP      404
9    OCT      359
10   NOV      310
11   DEC      337

In [52]:
pd.merge(df, popo, on='Month', how='inner')

   Month   "1958"_x   "1959"   "1960"   "1958"_y
0    JAN        340      360      417        340
1    FEB        318      342      391        318
2    MAR        362      406      419        362
3    APR        348      396      461        348
4    MAY        363      420      472        363
5    JUN        435      472      535        435
6    JUL        491      548      622        491
7    AUG        505      559      606        505
8    SEP        404      463      508        404
9    OCT        359      407      461        359
10   NOV        310      362      390        310
11   DEC        337      405      432        337

## Merging and Joining Data
You can combine multiple DataFrames using merge or join operations.

**Reference: merging**

```python
merged = pd.merge(df1, df2, on="common_column", how="inner")
merged = pd.merge(df1, df2, on="common_column", how="left")

merged = df1.merge(                            # the version you should actually write
    df2, on="common_column", how="left",
    validate="many_to_one", indicator=True,
)
```

`validate=` catches duplicate keys before they silently multiply your rows.
`indicator=True` adds a `_merge` column showing which side each row came from.

---

## Practice: Merging, joining and concatenating

`merge` joins **across**, adding columns. `concat` stacks **down**, adding rows.
Mixing these up is the most common beginner mistake in this section.

In [ ]:
import pandas as pd

orders = pd.read_csv("orders.csv", parse_dates=["order_date"])
customers = pd.read_csv("customers.csv", parse_dates=["signup_date"])

print(f"orders:    {orders.shape}, customer_ids: {sorted(orders['customer_id'].unique())}")
print(f"customers: {customers.shape}, customer_ids: {sorted(customers['customer_id'].unique())}")
print()
print("note: orders has customer 106 and 999, customers has 107. They do not match perfectly.")

In [ ]:
# The four join types, on data that deliberately does not line up
for how in ["inner", "left", "right", "outer"]:
    merged = orders.merge(customers, on="customer_id", how=how)
    print(f"{how:>6}: {len(merged)} rows, {merged['name'].isna().sum()} null names")

| `how` | Keeps | Use it when |
|---|---|---|
| `inner` | Only matching rows from both | You need complete records only |
| `left` | Every row from the left, nulls where no match | **The default in DE.** Keep all facts, enrich where possible |
| `right` | Every row from the right | Rare. Just swap the tables and use left |
| `outer` | Everything from both | Reconciliation, when you want to see both kinds of orphan |

`left` is the workhorse. You almost never want to silently lose fact rows, which is
what `inner` does.

In [ ]:
# indicator=True tells you where every row came from. Use it every time you investigate.
merged = orders.merge(customers, on="customer_id", how="outer", indicator=True)

print(merged["_merge"].value_counts())
print()
print("orders with no matching customer (orphan facts):")
print(merged[merged["_merge"] == "left_only"][["order_id", "customer_id", "item"]])
print()
print("customers with no orders (never bought anything):")
print(merged[merged["_merge"] == "right_only"][["customer_id", "name", "segment"]])

Those orphans are a real finding, not noise. Customer 999 on order 1012 does not
exist in the customer table, which usually means the two tables were extracted at
different times, or someone deleted a customer without cleaning up. Customer 107
signed up and never ordered, which is a marketing question rather than a bug.

In [ ]:
# validate= makes pandas check your assumption about the relationship
ok = orders.merge(customers, on="customer_id", how="left", validate="many_to_one")
print(f"many_to_one passed: {len(ok)} rows")

# Now break it: a duplicated customer row would silently multiply your revenue
broken_customers = pd.concat([customers, customers.iloc[[0]]], ignore_index=True)

try:
    orders.merge(broken_customers, on="customer_id", how="left", validate="many_to_one")
except Exception as e:
    print(f"caught: {type(e).__name__}: {str(e)[:80]}")

no_check = orders.merge(broken_customers, on="customer_id", how="left")
print(f"without validate: {len(orders)} orders became {len(no_check)} rows. Revenue now double counts.")

**Use `validate=` on every merge.** A duplicated key on the right-hand side silently
multiplies your rows, and the only symptom is that a number in a report is too big.
Nobody notices for three months. `validate="many_to_one"` turns that into an
exception the moment it happens.

In [ ]:
# Different column names on each side
left = orders.rename(columns={"customer_id": "cust"})
merged = left.merge(customers, left_on="cust", right_on="customer_id", how="left")
print(merged[["order_id", "cust", "name"]].head(3))

In [ ]:
# Overlapping column names get suffixed. Control the suffixes so the result is readable.
merged = orders.merge(customers, on="customer_id", how="left", suffixes=("_order", "_customer"))
print([c for c in merged.columns if "country" in c])
print()
print(merged[["order_id", "country_order", "country_customer"]].head(5))

Both tables have a `country` column, so pandas kept both and suffixed them. That is
also a free data quality check: if the order country and the customer country
disagree, something is worth looking at.

In [ ]:
mismatch = merged[
    merged["country_order"].notna()
    & merged["country_customer"].notna()
    & (merged["country_order"] != merged["country_customer"])
]
print(f"{len(mismatch)} order(s) where the order country differs from the customer country")
print(mismatch[["order_id", "name", "country_order", "country_customer"]])

In [ ]:
# concat: stacking two months of the same table
may = pd.read_csv("orders_may.csv", parse_dates=["order_date"])

stacked = pd.concat([orders, may], ignore_index=True)
print(f"{len(orders)} + {len(may)} = {len(stacked)} rows")
print(stacked.tail(4)[["order_id", "item", "order_date"]])

`ignore_index=True` renumbers the index. Without it you get two rows numbered 0,
two numbered 1, and every later `.loc` lookup becomes a surprise.

In [ ]:
# Stacking files that do not have identical columns
partial = pd.DataFrame({"order_id": [2001], "item": ["Cable"], "new_column": ["extra"]})
combined = pd.concat([orders.head(2), partial], ignore_index=True)

print(combined[["order_id", "item", "unit_price", "new_column"]])
print()
print("missing columns become NaN on both sides. concat does not complain.")

That silence is the danger. If a source file changes its column names, `concat`
happily produces a table where half the rows have nulls in the old column and half
in the new. Check your columns match before stacking.

In [ ]:
# A quick guard worth stealing
def safe_concat(frames, names=None):
    """Stack DataFrames, refusing if their columns do not match."""
    names = names or [f"frame_{i}" for i in range(len(frames))]
    base = set(frames[0].columns)
    for name, frame in zip(names[1:], frames[1:]):
        if set(frame.columns) != base:
            missing = base - set(frame.columns)
            extra = set(frame.columns) - base
            raise ValueError(f"{name}: missing {missing or 'none'}, extra {extra or 'none'}")
    return pd.concat(frames, ignore_index=True)


print(len(safe_concat([orders, may], ["april", "may"])))

try:
    safe_concat([orders, partial], ["orders", "partial"])
except ValueError as e:
    print(f"refused: {str(e)[:100]}")

### Your turn: tasks

**Task 1.** Left join `orders.csv` to `customers.csv` on `customer_id` and print the
order id, item and customer name.

**Task 2.** Do the same with an inner join and say in a comment how many rows you
lost, and which ones.

**DE Task 3.** Use `indicator=True` with an outer join to list every orphan order
(no matching customer) and every customer with no orders.

**DE Task 4.** Add `validate="many_to_one"` to your left join. Then deliberately
duplicate a customer row and show the error it raises.

**DE Task 5.** Stack `orders.csv` and `orders_may.csv`, reset the index, and print
total revenue per month across the combined table.

**DE Task 6.** After joining orders to customers, find any order where the order's
country does not match the customer's country, and print them.

**DE Task 7.** Write a function `join_report(left, right, key)` that performs an outer
merge with an indicator and prints: rows matched, left only, right only, and the
match rate as a percentage.

In [ ]:
# Task 1 answer

In [ ]:
# Task 2 answer

In [ ]:
# DE Task 3 answer

In [ ]:
# DE Task 4 answer

In [ ]:
# DE Task 5 answer

In [ ]:
# DE Task 6 answer

In [ ]:
# DE Task 7 answer

## Sorting Data
Sorting can help organize your data based on a specific column or set of columns.

**Reference: sorting**

```python
df.sort_values("column_name")
df.sort_values("column_name", ascending=False)
df.sort_values(["column1", "column2"], ascending=[True, False])
df.sort_values("column_name", na_position="first")     # surface the nulls
```

## Data Transformation
Pandas allows you to apply custom functions to modify or create new data.

**Reference: transformation**

```python
df["new_column"] = df["column_name"] * 2          # vectorised. always prefer this
df["new_column"] = df["column_name"].apply(lambda x: x * 2)   # slower
df_transformed = df.map(lambda x: x + 1)          # every cell
```

**Note:** `DataFrame.applymap` was deprecated in pandas 2.1 and removed in 3.0.
Use `DataFrame.map` instead. Worked examples, including a timing comparison, are in
the practice section below.

---

## Practice: Transforming columns

### Vectorised first, `apply` second, loops never

Pandas operates on whole columns at once. That is the point of it. Writing a Python
loop over rows gives up the only advantage pandas has.

In [ ]:
import pandas as pd, time
orders = pd.read_csv("orders.csv", parse_dates=["order_date"])

# Vectorised: one operation on the whole column
orders["revenue"] = orders["quantity"] * orders["unit_price"]
orders["vat"] = orders["revenue"] * 0.075
orders["total"] = orders["revenue"] + orders["vat"]

orders[["order_id", "quantity", "unit_price", "revenue", "vat", "total"]].head()

In [ ]:
# How much does it matter? Build a bigger frame and time all three approaches.
big = pd.concat([orders] * 4000, ignore_index=True)
print(f"{len(big):,} rows")

start = time.perf_counter()
result_vec = big["quantity"] * big["unit_price"]
t_vec = time.perf_counter() - start

start = time.perf_counter()
result_apply = big.apply(lambda row: row["quantity"] * row["unit_price"], axis=1)
t_apply = time.perf_counter() - start

start = time.perf_counter()
values = []
for _, row in big.iterrows():
    values.append(row["quantity"] * row["unit_price"])
t_loop = time.perf_counter() - start

print(f"vectorised:      {t_vec * 1000:8.1f} ms   (1x)")
print(f"apply(axis=1):   {t_apply * 1000:8.1f} ms   ({t_apply / t_vec:.0f}x slower)")
print(f"iterrows loop:   {t_loop * 1000:8.1f} ms   ({t_loop / t_vec:.0f}x slower)")

Same answer, wildly different cost. On a few hundred rows nobody notices. On ten
million, vectorised finishes while `iterrows` is still going at lunchtime.

**Reach for `apply` only when the logic genuinely cannot be expressed as column
arithmetic.** Reach for `iterrows` essentially never.

In [ ]:
# apply on a single column is fine and readable
orders["price_band"] = orders["unit_price"].apply(
    lambda price: "unknown" if pd.isna(price) else ("high" if price > 100000 else "low")
)
print(orders[["order_id", "unit_price", "price_band"]].head(6))

In [ ]:
# But np.where or np.select is faster and clearer for conditional columns
import numpy as np

orders["band"] = np.where(orders["unit_price"] > 100000, "high", "low")

conditions = [
    orders["unit_price"].isna(),
    orders["unit_price"] > 400000,
    orders["unit_price"] > 50000,
]
labels = ["unknown", "premium", "mid"]
orders["tier"] = np.select(conditions, labels, default="budget")

orders[["order_id", "unit_price", "band", "tier"]].head(8)

`np.select` reads top to bottom like an `if/elif/else` chain, and the first matching
condition wins. It is the pandas equivalent of a SQL `CASE WHEN`.

In [ ]:
# map() on a Series: swap values using a dictionary
country_names = {"NG": "Nigeria", "GH": "Ghana", "KE": "Kenya"}
orders["country_full"] = orders["country"].map(country_names)

print(orders[["country", "country_full"]].drop_duplicates())

Anything not in the dictionary becomes `NaN`. That is useful: it tells you about
codes you did not know existed. Use `.map(d).fillna("unknown")` if you would rather
not lose them.

In [ ]:
# DataFrame.map applies to every cell.
# Note: the old name was applymap. It was deprecated in pandas 2.1 and REMOVED in 3.0.
numeric = orders[["quantity", "unit_price"]]

try:
    doubled = numeric.map(lambda x: x * 2)              # pandas 2.1+
    print("used DataFrame.map")
except AttributeError:
    doubled = numeric.applymap(lambda x: x * 2)         # older pandas
    print("fell back to applymap (old pandas)")

doubled.head(3)

If you have `df.applymap(...)` anywhere in your own code, change it to `df.map(...)`
now. It still works with a warning on pandas 2.x and fails outright on 3.x.

In [ ]:
# Renaming, dropping, reordering
renamed = orders.rename(columns={"unit_price": "price", "order_date": "date"})
print(list(renamed.columns)[:6])

dropped = orders.drop(columns=["band", "tier", "price_band"])
print(f"{orders.shape[1]} columns -> {dropped.shape[1]} columns")

reordered = orders[["order_id", "order_date", "customer_id", "item", "revenue"]]
reordered.head(3)

In [ ]:
# assign(): build several columns in one readable chain
report = (
    pd.read_csv("orders.csv", parse_dates=["order_date"])
    .assign(
        revenue=lambda d: d["quantity"] * d["unit_price"],
        vat=lambda d: d["revenue"] * 0.075,
        month=lambda d: d["order_date"].dt.strftime("%Y-%m"),
        is_large=lambda d: d["revenue"] > 200000,
    )
    .query("status == 'completed'")
    .sort_values("revenue", ascending=False)
    .head(5)
)

report[["order_id", "item", "revenue", "vat", "month", "is_large"]]

Each `lambda d:` receives the DataFrame as it exists at that point in the chain,
so `vat` can use the `revenue` that the line above just created. Chains like this
read top to bottom as a list of steps, and there are no intermediate variables to
get stale.

In [ ]:
# Sorting properly
print(orders.sort_values("revenue", ascending=False)[["order_id", "revenue"]].head(3))
print()
print(orders.sort_values(["country", "revenue"], ascending=[True, False])
      [["country", "order_id", "revenue"]].head(8))
print()
print("nulls go last by default. na_position='first' surfaces them:")
print(orders.sort_values("unit_price", na_position="first")[["order_id", "unit_price"]].head(3))

### Your turn: tasks

**Task 1.** Add `revenue`, `vat` (7.5%) and `total` columns to `orders.csv`, all
vectorised.

**Task 2.** Add a `size` column that says `"large"` when revenue is over 200,000 and
`"small"` otherwise, using `np.where`.

**Task 3.** Use `np.select` to add a `tier` column: `"premium"` over 400,000,
`"mid"` over 50,000, `"budget"` otherwise, and `"unknown"` where the price is null.

**Task 4.** Map the `status` column to friendly labels using a dictionary:
`completed -> Done`, `pending -> In progress`, `cancelled -> Cancelled`.

**DE Task 5.** Rebuild Tasks 1 to 3 as a single `.assign()` chain that also filters to
completed orders and sorts by revenue.

**DE Task 6.** Rename every column of `orders.csv` to snake_case, drop `quantity` and
`status`, and reorder so `order_id` and `order_date` come first.

**DE Task 7.** Time the vectorised revenue calculation against `apply(axis=1)` on a
frame of at least 50,000 rows, and print how many times slower `apply` was.

In [ ]:
# Task 1 answer

In [ ]:
# Task 2 answer

In [ ]:
# Task 3 answer

In [ ]:
# Task 4 answer

In [ ]:
# DE Task 5 answer

In [ ]:
# DE Task 6 answer

In [ ]:
# DE Task 7 answer

## Pivot Tables
Pivot tables help summarize data by grouping and aggregating specific columns.

**Reference: pivot tables**

```python
pivot = df.pivot_table(
    values="value_column",
    index="category_column",
    columns="pivot_column",
    aggfunc="sum",
    fill_value=0,
    margins=True,        # adds a total row and column
)
```

## Concatenating DataFrames
You can concatenate multiple DataFrames either vertically (row-wise) or horizontally (column-wise).

In [55]:
pd.concat([df, popo], axis=1)

   Month   "1958"   "1959"   "1960" Month   "1958"
0    JAN      340      360      417   JAN      340
1    FEB      318      342      391   FEB      318
2    MAR      362      406      419   MAR      362
3    APR      348      396      461   APR      348
4    MAY      363      420      472   MAY      363
5    JUN      435      472      535   JUN      435
6    JUL      491      548      622   JUL      491
7    AUG      505      559      606   AUG      505
8    SEP      404      463      508   SEP      404
9    OCT      359      407      461   OCT      359
10   NOV      310      362      390   NOV      310
11   DEC      337      405      432   DEC      337

**Reference: concatenating**

```python
df_combined = pd.concat([df1, df2], axis=0, ignore_index=True)   # stack rows
df_combined = pd.concat([df1, df2], axis=1)                      # side by side
```

Always pass `ignore_index=True` when stacking, or you end up with duplicate index
values and every later `.loc` lookup surprises you.

## Exporting Data
Once your data is manipulated and processed, you can export it to various formats such as CSV, Excel, or JSON.

In [56]:
# Exporting a DataFrame to CSV
df.to_csv('final_output.csv', index=False)

# Exporting a DataFrame to Excel
df.to_excel('final_output.xlsx', index=False)

# Exporting a DataFrame to JSON
df.to_json('final_output.json')

---

## Practice: Exporting

### `index=False`, almost always

In [ ]:
import pandas as pd
orders = pd.read_csv("orders.csv", parse_dates=["order_date"])
orders["revenue"] = orders["quantity"] * orders["unit_price"]

orders.to_csv("with_index.csv")                    # the default
orders.to_csv("without_index.csv", index=False)    # what you almost always want

with open("with_index.csv", encoding="utf-8") as f:
    print("with index:")
    print(f.readline())

with open("without_index.csv", encoding="utf-8") as f:
    print("without index:")
    print(f.readline())

The default writes the row numbers as an unnamed first column. Read that file back
and you get a mystery column called `Unnamed: 0`. Pass `index=False` unless the index
genuinely carries meaning, such as a date index on a time series.

In [ ]:
# The formats, and when each is right
orders.to_csv("out.csv", index=False)
orders.to_json("out.json", orient="records", indent=2, date_format="iso")
orders.to_json("out.jsonl", orient="records", lines=True, date_format="iso")

try:
    orders.to_parquet("out.parquet", index=False)
    parquet_ok = True
except Exception as e:
    parquet_ok = False
    print(f"parquet needs pyarrow: {type(e).__name__}")

import os
for name in ["out.csv", "out.json", "out.jsonl"] + (["out.parquet"] if parquet_ok else []):
    print(f"{name:<14} {os.path.getsize(name):>7} bytes")

| Format | Use it for | Watch out |
|---|---|---|
| CSV | Sharing with humans, Excel, anything | No types. Everything comes back as text |
| JSON | Config, API payloads, nested data | Whole file must be read at once |
| JSONL | Events, logs, append-only streams | One object per line |
| **Parquet** | **Anything going into a warehouse** | Needs `pyarrow`, not human readable |

Parquet keeps your dtypes, compresses far smaller, and lets a query engine read just
the columns it needs. Once data leaves the exploration stage, Parquet is the default
in every warehouse you will work with. CSV is for handing to a person.

In [ ]:
# Writing partitioned output, the shape a warehouse expects
import os

df = orders.dropna(subset=["order_date"]).copy()
df["partition"] = df["order_date"].dt.strftime("%Y-%m")

for partition, group in df.groupby("partition"):
    folder = os.path.join("output", f"month={partition}")
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, "orders.csv")
    group.drop(columns=["partition"]).to_csv(path, index=False)
    print(f"{path}  ({len(group)} rows)")

`month=2026-01` as a folder name is Hive-style partitioning. Every engine you will
meet, from Spark to BigQuery to DuckDB, reads that layout and can skip whole folders
when your query filters on the month. Writing it this way is free, and it makes
queries that scan a year of data read only the months they need.

In [ ]:
# Reading a whole partitioned folder back in
import glob

frames = []
for path in sorted(glob.glob("output/**/*.csv", recursive=True)):
    part = pd.read_csv(path)
    part["source_file"] = path
    frames.append(part)

combined = pd.concat(frames, ignore_index=True)
print(f"{len(frames)} file(s) -> {len(combined)} rows")
print(combined["source_file"].value_counts())

---

## End of class mini project: an orders report

One pass over real, imperfect data. Everything you need is in this notebook already.

The data has: a duplicate row, a missing price, a missing date, an order whose
customer does not exist, and a customer who never ordered. That is a normal Tuesday.

In [ ]:
import pandas as pd

orders = pd.read_csv("orders.csv")
customers = pd.read_csv("customers.csv")

print(f"orders:    {orders.shape}")
print(f"customers: {customers.shape}")
orders.head()

### What to build

**1. Profile.** Print the shape, dtypes, null count and null percentage per column,
the number of fully duplicated rows and the number of duplicate `order_id` values.

**2. Clean.**
   - Parse `order_date` as a real date with `errors="coerce"`, and report how many
     failed
   - Convert `unit_price` with `to_numeric(errors="coerce")`, and report how many
     became null
   - Drop duplicate `order_id` values, keeping the first, and report how many went
   - Standardise the column names to snake_case
   - Keep a `rejected` DataFrame of everything you removed, with a `reason` column

**3. Enrich.** Add `revenue` (quantity times unit price), `vat` at 7.5%, `total`,
`month` as `YYYY-MM`, and a `tier` column using `np.select`
(premium over 400,000, mid over 50,000, budget otherwise, unknown when null).

**4. Join.** Left join to `customers.csv` with `validate="many_to_one"`, using
`indicator=True`. Report how many orders had no matching customer, and list them.

**5. Aggregate.** Produce three summary tables:
   - Revenue, order count and distinct customers per `country`
   - Revenue per `category` per `month`
   - Revenue per customer `segment`, including average order value

**6. Data quality report.** Print: rows in, rows kept, rows rejected with reasons,
rejection rate, null rate per column after cleaning, orphan orders, and the total
revenue. Only count `completed` orders in the revenue figure, and say so.

**7. Export.** Write the clean table to `clean_orders.csv` with `index=False`, the
country summary to `summary_by_country.csv`, and the rejected rows to
`rejected_orders.csv`.

### Stretch goals

8. Write the clean table partitioned by month into `output/month=YYYY-MM/`, read it
   all back, and confirm the row count and total revenue match.
9. Add a `pct_of_country_revenue` column using `transform`.
10. Build a pivot table of revenue with `country` down the side and `month` across,
    with totals in the margins.
11. Wrap the whole thing in functions (`profile`, `clean`, `enrich`, `join_customers`,
    `summarise`, `report`, `run`) so it could be scheduled tomorrow.

In [ ]:
# 1. profile

In [ ]:
# 2. clean

In [ ]:
# 3. enrich

In [ ]:
# 4. join

In [ ]:
# 5. aggregate

In [ ]:
# 6. data quality report

In [ ]:
# 7. export

---

## Pandas to SQL, side by side

You already know SQL. This table is the shortest path to being useful in pandas.

| SQL | pandas |
|---|---|
| `SELECT * FROM t` | `df` |
| `SELECT a, b FROM t` | `df[["a", "b"]]` |
| `SELECT * FROM t LIMIT 5` | `df.head(5)` |
| `SELECT DISTINCT a FROM t` | `df["a"].unique()` or `df.drop_duplicates(subset=["a"])` |
| `COUNT(DISTINCT a)` | `df["a"].nunique()` |
| `WHERE a > 10` | `df[df["a"] > 10]` |
| `WHERE a > 10 AND b = 'x'` | `df[(df["a"] > 10) & (df["b"] == "x")]` |
| `WHERE a IN (1, 2)` | `df[df["a"].isin([1, 2])]` |
| `WHERE a BETWEEN 1 AND 9` | `df[df["a"].between(1, 9)]` |
| `WHERE a IS NULL` | `df[df["a"].isna()]` |
| `WHERE a LIKE '%lap%'` | `df[df["a"].str.contains("lap", na=False)]` |
| `ORDER BY a DESC` | `df.sort_values("a", ascending=False)` |
| `GROUP BY a` | `df.groupby("a")` |
| `SELECT a, SUM(b) FROM t GROUP BY a` | `df.groupby("a")["b"].sum().reset_index()` |
| `HAVING SUM(b) > 100` | `.groupby("a").filter(lambda g: g["b"].sum() > 100)` |
| `SUM(b) OVER (PARTITION BY a)` | `df.groupby("a")["b"].transform("sum")` |
| `JOIN ... ON id` | `left.merge(right, on="id", how="inner")` |
| `LEFT JOIN` | `how="left"` |
| `UNION ALL` | `pd.concat([df1, df2], ignore_index=True)` |
| `CASE WHEN ... THEN ...` | `np.select(conditions, labels, default=...)` |
| `COALESCE(a, 0)` | `df["a"].fillna(0)` |
| `CAST(a AS FLOAT)` | `pd.to_numeric(df["a"], errors="coerce")` |
| `CREATE TABLE AS ...` | `df.to_parquet(path)` |

Two habits SQL does not teach you, that pandas needs:

- **`.copy()`** when you filter and then intend to modify the result
- **`validate=`** on every merge, because pandas will happily fan out your rows

---

## Common mistakes to watch for

| Mistake | What you see | The fix |
|---|---|---|
| `and` / `or` in a filter | "truth value of a Series is ambiguous" | `&`, `\|`, `~` |
| Missing parentheses in a filter | Confusing `TypeError` | `(df["a"] > 1) & (df["b"] == 2)` |
| `df[mask]["col"] = x` | `SettingWithCopyWarning`, change may not stick | `df.loc[mask, "col"] = x` |
| Filtering then assigning | Same warning | `df[mask].copy()` first |
| `df.shape()` | `TypeError: not callable` | `df.shape`, no parentheses |
| `df.head` | Prints `<bound method ...>` | `df.head()`, with parentheses |
| `loc[0:3]` expecting 3 rows | You get 4 | `loc` includes the stop, `iloc` does not |
| `df.mean()` on mixed types | `TypeError` | `df.mean(numeric_only=True)` |
| Bare `dropna()` | Most of your data disappears | `dropna(subset=["the_column"])` |
| `astype(float)` on messy text | `ValueError` on one bad row | `pd.to_numeric(..., errors="coerce")` |
| Merge without `validate=` | Row count quietly multiplies | `validate="many_to_one"` |
| `inner` join by default habit | Fact rows silently vanish | `how="left"` unless you mean otherwise |
| `concat` with mismatched columns | Half your rows full of nulls | Check columns match first |
| `concat` without `ignore_index` | Duplicate index values | `ignore_index=True` |
| `to_csv()` without `index=False` | An `Unnamed: 0` column next time | `index=False` |
| `iterrows` for arithmetic | 100x slower than it needs to be | Vectorise, or `apply` at worst |
| `df.applymap` | Deprecated in 2.1, gone in 3.0 | `df.map` |
| Chained indexing `df["a"]["b"]` | Unpredictable | `df.loc[row, "col"]` |

In [ ]:
# One last habit: check your row count after every merge. Every single time.
import pandas as pd

orders = pd.read_csv("orders.csv")
customers = pd.read_csv("customers.csv")

before = len(orders)
merged = orders.merge(customers, on="customer_id", how="left", validate="many_to_one")
after = len(merged)

print(f"before: {before}, after: {after}")
if after != before:
    print("STOP. A left join must never change the row count. Your right table has duplicate keys.")
else:
    print("row count preserved, join is safe")

In [ ]:
# Clean up everything this notebook created.
# Run this only when you are finished.
import os, glob, shutil

for name in ["airtravel.csv", "orders.csv", "customers.csv", "orders_may.csv",
             "output.csv", "popo.csv", "final_output.csv", "final_output.xlsx",
             "final_output.json", "with_index.csv", "without_index.csv",
             "out.csv", "out.json", "out.jsonl", "out.parquet",
             "clean_orders.csv", "summary_by_country.csv", "rejected_orders.csv"]:
    if os.path.isfile(name):
        os.remove(name)

if os.path.isdir("output"):
    shutil.rmtree("output")

print("cleaned up. re-run the setup cell at the top to start over")