# Data Manipulation with Pandas

Pandas is a powerful Python library for data manipulation and analysis, particularly useful when working with structured data. Let's explore how to use it effectively.

## Importing Pandas
The first step in using pandas is to import the library.

In [1]:
import pandas as pd

In [11]:
df= pd.read_csv('airtravel.csv')

In [12]:
df.head()

  Month   "1958"   "1959"   "1960"
0   JAN      340      360      417
1   FEB      318      342      391
2   MAR      362      406      419
3   APR      348      396      461
4   MAY      363      420      472

In [17]:
df.head(3)

  Month   "1958"   "1959"   "1960"
0   JAN      340      360      417
1   FEB      318      342      391
2   MAR      362      406      419

In [13]:
df.tail()

   Month   "1958"   "1959"   "1960"
7    AUG      505      559      606
8    SEP      404      463      508
9    OCT      359      407      461
10   NOV      310      362      390
11   DEC      337      405      432

In [20]:
df.sample(5)

   Month   "1958"   "1959"   "1960"
7    AUG      505      559      606
11   DEC      337      405      432
6    JUL      491      548      622
2    MAR      362      406      419
8    SEP      404      463      508

## Reading Data
Pandas can read data from various formats such as CSV, Excel, JSON, and SQL. Here, we will focus on reading from CSV.

In [21]:
# Reading a CSV file into a DataFrame
df = pd.read_csv('airtravel.csv')
print(df.head())  # Display the first 5 rows of the DataFrame

  Month   "1958"   "1959"   "1960"
0   JAN      340      360      417
1   FEB      318      342      391
2   MAR      362      406      419
3   APR      348      396      461
4   MAY      363      420      472

In [22]:
df

   Month   "1958"   "1959"   "1960"
0    JAN      340      360      417
1    FEB      318      342      391
2    MAR      362      406      419
3    APR      348      396      461
4    MAY      363      420      472
5    JUN      435      472      535
6    JUL      491      548      622
7    AUG      505      559      606
8    SEP      404      463      508
9    OCT      359      407      461
10   NOV      310      362      390
11   DEC      337      405      432

## Writing Data
You can write DataFrames to different formats. Here’s how to write data back to a CSV file.

In [26]:
df.to_csv("lahya.csv")

In [27]:
# Writing a DataFrame to a CSV file
df.to_csv('output.csv', index=False)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Month    12 non-null     object
 1    "1958"  12 non-null     int64
 2    "1959"  12 non-null     int64
 3    "1960"  12 non-null     int64
dtypes: int64(3), object(1)
memory usage: 516.0+ bytes

In [30]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Month    12 non-null     object
 1    "1958"  12 non-null     int64
 2    "1959"  12 non-null     int64
 3    "1960"  12 non-null     int64
dtypes: int64(3), object(1)
memory usage: 516.0+ bytes
None

In [29]:
print(df.describe())

           "1958"      "1959"      "1960"
count   12.000000   12.000000   12.000000
mean   381.000000  428.333333  476.166667
std     64.530472   69.830097   77.737125
min    310.000000  342.000000  390.000000
25%    339.250000  387.500000  418.500000
50%    360.500000  406.500000  461.000000
75%    411.750000  465.250000  514.750000
max    505.000000  559.000000  622.000000

In [31]:
print(df.columns)

Index(['Month', ' "1958"', ' "1959"', ' "1960"'], dtype='object')

In [29]:
print(df.shape)

(12, 4)

## Inspecting Data
When working with large datasets, it's important to inspect the data to understand its structure.

In [32]:
# Viewing basic information about the DataFrame
print(df.info())  # Shows column data types and non-null counts
print(df.describe())  # Summary statistics for numerical columns
print(df.columns)  # Column names
print(df.shape)  # Dimensions of the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Month    12 non-null     object
 1    "1958"  12 non-null     int64
 2    "1959"  12 non-null     int64
 3    "1960"  12 non-null     int64
dtypes: int64(3), object(1)
memory usage: 516.0+ bytes
None
           "1958"      "1959"      "1960"
count   12.000000   12.000000   12.000000
mean   381.000000  428.333333  476.166667
std     64.530472   69.830097   77.737125
min    310.000000  342.000000  390.000000
25%    339.250000  387.500000  418.500000
50%    360.500000  406.500000  461.000000
75%    411.750000  465.250000  514.750000
max    505.000000  559.000000  622.000000
Index(['Month', ' "1958"', ' "1959"', ' "1960"'], dtype='object')
(12, 4)

## Selecting Data
You can select specific rows, columns, or subsets of your DataFrame using different methods.

In [35]:
df.head(2)

  Month   "1958"   "1959"   "1960"
0   JAN      340      360      417
1   FEB      318      342      391

In [36]:
df.columns

Index(['Month', ' "1958"', ' "1959"', ' "1960"'], dtype='object')

In [44]:
 df[['Month', ' "1958"']]

   Month   "1958"
0    JAN      340
1    FEB      318
2    MAR      362
3    APR      348
4    MAY      363
5    JUN      435
6    JUL      491
7    AUG      505
8    SEP      404
9    OCT      359
10   NOV      310
11   DEC      337

In [45]:
osas = df[['Month', ' "1958"']]

In [47]:
osas.to_csv('osas.csv')

In [61]:
df[df[' "1958"'] > 400]

  Month   "1958"   "1959"   "1960"
5   JUN      435      472      535
6   JUL      491      548      622
7   AUG      505      559      606
8   SEP      404      463      508

In [41]:
print(df[df[' "1958"'] > 400])

  Month   "1958"   "1959"   "1960"
5   JUN      435      472      535
6   JUL      491      548      622
7   AUG      505      559      606
8   SEP      404      463      508

In [ ]:
# Selecting a column
print(df['column_name'])

# Selecting multiple columns
print(df[['column1', 'column2']])

# Selecting rows by index
print(df.iloc[0])  # First row
print(df.iloc[0:3])  # First 3 rows

# Selecting rows by condition
print(df[df['column_name'] > 10])  # Rows where the value in 'column_name' is greater than 10

## Filtering Data
Filtering allows you to extract specific data based on conditions.

In [ ]:
# Filtering rows where a column value meets a condition
filtered_df = df[df['column_name'] > threshold]
print(filtered_df)

In [ ]:
1, 3, 4, 2, 3, 5, 2, 3, 10, 25

## Handling Missing Data
Pandas provides easy ways to detect, fill, or drop missing values.

In [48]:
df.dropna()

   Month   "1958"   "1959"   "1960"
0    JAN      340      360      417
1    FEB      318      342      391
2    MAR      362      406      419
3    APR      348      396      461
4    MAY      363      420      472
5    JUN      435      472      535
6    JUL      491      548      622
7    AUG      505      559      606
8    SEP      404      463      508
9    OCT      359      407      461
10   NOV      310      362      390
11   DEC      337      405      432

In [ ]:
# Checking for missing values
print(df.isnull().sum())  # Count of missing values in each column

# Dropping rows or columns with missing values
df_cleaned = df.dropna()  # Drop rows with any missing values
df_cleaned = df.dropna(axis=1)  # Drop columns with any missing values

# Filling missing values
df_filled = df.fillna(0)  # Replace missing values with 0
df_filled = df.fillna(df.mean())  # Replace missing values with the column mean

## Grouping and Aggregating Data
Pandas makes it easy to group data by certain columns and perform aggregate operations (like sum, mean, etc.).

In [ ]:
# Grouping data by a column and calculating the mean
grouped_df = df.groupby('category_column').mean()
print(grouped_df)

# Aggregating multiple statistics for each group
grouped_df = df.groupby('category_column').agg({'column1': 'mean', 'column2': 'sum'})
print(grouped_df)

In [53]:
popo

   Month   "1958"
0    JAN      340
1    FEB      318
2    MAR      362
3    APR      348
4    MAY      363
5    JUN      435
6    JUL      491
7    AUG      505
8    SEP      404
9    OCT      359
10   NOV      310
11   DEC      337

In [55]:
pd.merge(df, osas, on='Month', how='inner')

   Month   "1958"_x   "1959"   "1960"   "1958"_y
0    JAN        340      360      417        340
1    FEB        318      342      391        318
2    MAR        362      406      419        362
3    APR        348      396      461        348
4    MAY        363      420      472        363
5    JUN        435      472      535        435
6    JUL        491      548      622        491
7    AUG        505      559      606        505
8    SEP        404      463      508        404
9    OCT        359      407      461        359
10   NOV        310      362      390        310
11   DEC        337      405      432        337

## Merging and Joining Data
You can combine multiple DataFrames using merge or join operations.

In [ ]:
# Merging two DataFrames on a common column
merged_df = pd.merge(df1, df2, on='common_column', how='inner')  # Inner join
merged_df = pd.merge(df1, df2, on='common_column', how='left')   # Left join

## Sorting Data
Sorting can help organize your data based on a specific column or set of columns.

In [56]:
df.columns

Index(['Month', ' "1958"', ' "1959"', ' "1960"'], dtype='object')

In [ ]:
# Sorting by a single column
sorted_df = df.sort_values('column_name')

# Sorting by multiple columns
sorted_df = df.sort_values(['column1', 'column2'], ascending=[True, False])

## Data Transformation
Pandas allows you to apply custom functions to modify or create new data.

In [ ]:
# Applying a function to a column
df['new_column'] = df['column_name'].apply(lambda x: x * 2)

# Applying a function to every element in the DataFrame
df_transformed = df.applymap(lambda x: x + 1)
print(df_transformed)

## Pivot Tables
Pivot tables help summarize data by grouping and aggregating specific columns.

In [ ]:
# Creating a pivot table
pivot_table = df.pivot_table(values='value_column', index='category_column', columns='pivot_column', aggfunc='sum')
print(pivot_table)

## Concatenating DataFrames
You can concatenate multiple DataFrames either vertically (row-wise) or horizontally (column-wise).

In [60]:
pd.concat([df, osas], axis=1)

   Month   "1958"   "1959"   "1960" Month   "1958"
0    JAN      340      360      417   JAN      340
1    FEB      318      342      391   FEB      318
2    MAR      362      406      419   MAR      362
3    APR      348      396      461   APR      348
4    MAY      363      420      472   MAY      363
5    JUN      435      472      535   JUN      435
6    JUL      491      548      622   JUL      491
7    AUG      505      559      606   AUG      505
8    SEP      404      463      508   SEP      404
9    OCT      359      407      461   OCT      359
10   NOV      310      362      390   NOV      310
11   DEC      337      405      432   DEC      337

In [ ]:
# Concatenating DataFrames vertically (stacking)
df_combined = pd.concat([df1, df2], axis=0)

# Concatenating DataFrames horizontally (side-by-side)
df_combined = pd.concat([df1, df2], axis=1)

## Exporting Data
Once your data is manipulated and processed, you can export it to various formats such as CSV, Excel, or JSON.

In [56]:
# Exporting a DataFrame to CSV
df.to_csv('final_output.csv', index=False)

# Exporting a DataFrame to Excel
df.to_excel('final_output.xlsx', index=False)

# Exporting a DataFrame to JSON
df.to_json('final_output.json')